// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: protobufStorage.proto

package protobufStorage

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OpType int32

const (
	OpType_OP_POST         OpType = 0 // add a message to a topic
	OpType_OP_LIKE         OpType = 1 // like a message
	OpType_OP_CREATE_USER  OpType = 2 // create a new user
	OpType_OP_CREATE_TOPIC OpType = 3 // create a new topic
)

// Enum value maps for OpType.
var (
	OpType_name = map[int32]string{
		0: "OP_POST",
		1: "OP_LIKE",
		2: "OP_CREATE_USER",
		3: "OP_CREATE_TOPIC",
	}
	OpType_value = map[string]int32{
		"OP_POST":         0,
		"OP_LIKE":         1,
		"OP_CREATE_USER":  2,
		"OP_CREATE_TOPIC": 3,
	}
)

func (x OpType) Enum() *OpType {
	p := new(OpType)
	*p = x
	return p
}

func (x OpType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OpType) Descriptor() protoreflect.EnumDescriptor {
	return file_protobufStorage_proto_enumTypes[0].Descriptor()
}

func (OpType) Type() protoreflect.EnumType {
	return &file_protobufStorage_proto_enumTypes[0]
}

func (x OpType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OpType.Descriptor instead.
func (OpType) EnumDescriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{0}
}

type ServerRole int32

const (
	ServerRole_HEAD   ServerRole = 0
	ServerRole_MIDDLE ServerRole = 1
	ServerRole_TAIL   ServerRole = 2
)

// Enum value maps for ServerRole.
var (
	ServerRole_name = map[int32]string{
		0: "HEAD",
		1: "MIDDLE",
		2: "TAIL",
	}
	ServerRole_value = map[string]int32{
		"HEAD":   0,
		"MIDDLE": 1,
		"TAIL":   2,
	}
)

func (x ServerRole) Enum() *ServerRole {
	p := new(ServerRole)
	*p = x
	return p
}

func (x ServerRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ServerRole) Descriptor() protoreflect.EnumDescriptor {
	return file_protobufStorage_proto_enumTypes[1].Descriptor()
}

func (ServerRole) Type() protoreflect.EnumType {
	return &file_protobufStorage_proto_enumTypes[1]
}

func (x ServerRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ServerRole.Descriptor instead.
func (ServerRole) EnumDescriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{1}
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_protobufStorage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{0}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Topic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Topic) Reset() {
	*x = Topic{}
	mi := &file_protobufStorage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Topic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Topic) ProtoMessage() {}

func (x *Topic) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Topic.ProtoReflect.Descriptor instead.
func (*Topic) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{1}
}

func (x *Topic) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Topic) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TopicId       int64                  `protobuf:"varint,2,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Likes         int32                  `protobuf:"varint,6,opt,name=likes,proto3" json:"likes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_protobufStorage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{2}
}

func (x *Message) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *Message) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Message) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Message) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Message) GetLikes() int32 {
	if x != nil {
		return x.Likes
	}
	return 0
}

type Like struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // user who liked the message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Like) Reset() {
	*x = Like{}
	mi := &file_protobufStorage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Like) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Like) ProtoMessage() {}

func (x *Like) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Like.ProtoReflect.Descriptor instead.
func (*Like) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{3}
}

func (x *Like) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *Like) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *Like) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type NodeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeInfo) Reset() {
	*x = NodeInfo{}
	mi := &file_protobufStorage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeInfo) ProtoMessage() {}

func (x *NodeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeInfo.ProtoReflect.Descriptor instead.
func (*NodeInfo) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{4}
}

func (x *NodeInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NodeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_protobufStorage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{5}
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateTopicRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTopicRequest) Reset() {
	*x = CreateTopicRequest{}
	mi := &file_protobufStorage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTopicRequest) ProtoMessage() {}

func (x *CreateTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTopicRequest.ProtoReflect.Descriptor instead.
func (*CreateTopicRequest) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTopicRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type PostMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostMessageRequest) Reset() {
	*x = PostMessageRequest{}
	mi := &file_protobufStorage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostMessageRequest) ProtoMessage() {}

func (x *PostMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostMessageRequest.ProtoReflect.Descriptor instead.
func (*PostMessageRequest) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{7}
}

func (x *PostMessageRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *PostMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PostMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type LikeMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	MessageId     int64                  `protobuf:"varint,2,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        int64                  `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // user who posted the like
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LikeMessageRequest) Reset() {
	*x = LikeMessageRequest{}
	mi := &file_protobufStorage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LikeMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LikeMessageRequest) ProtoMessage() {}

func (x *LikeMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LikeMessageRequest.ProtoReflect.Descriptor instead.
func (*LikeMessageRequest) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{8}
}

func (x *LikeMessageRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *LikeMessageRequest) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *LikeMessageRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListTopicsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topics        []*Topic               `protobuf:"bytes,1,rep,name=topics,proto3" json:"topics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTopicsResponse) Reset() {
	*x = ListTopicsResponse{}
	mi := &file_protobufStorage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTopicsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTopicsResponse) ProtoMessage() {}

func (x *ListTopicsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTopicsResponse.ProtoReflect.Descriptor instead.
func (*ListTopicsResponse) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{9}
}

func (x *ListTopicsResponse) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TopicId       int64                  `protobuf:"varint,1,opt,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	FromMessageId int64                  `protobuf:"varint,2,opt,name=from_message_id,json=fromMessageId,proto3" json:"from_message_id,omitempty"` // starting id of the message (0 from beginning)
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                                        // max number of messages
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_protobufStorage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{10}
}

func (x *GetMessagesRequest) GetTopicId() int64 {
	if x != nil {
		return x.TopicId
	}
	return 0
}

func (x *GetMessagesRequest) GetFromMessageId() int64 {
	if x != nil {
		return x.FromMessageId
	}
	return 0
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_protobufStorage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{11}
}

func (x *GetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SubscribeTopicRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TopicId        []int64                `protobuf:"varint,1,rep,packed,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FromMessageId  int64                  `protobuf:"varint,3,opt,name=from_message_id,json=fromMessageId,proto3" json:"from_message_id,omitempty"` // starting id of the message
	SubscribeToken string                 `protobuf:"bytes,4,opt,name=subscribe_token,json=subscribeToken,proto3" json:"subscribe_token,omitempty"` // token generated by the head used to authorize the subscription
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscribeTopicRequest) Reset() {
	*x = SubscribeTopicRequest{}
	mi := &file_protobufStorage_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeTopicRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeTopicRequest) ProtoMessage() {}

func (x *SubscribeTopicRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeTopicRequest.ProtoReflect.Descriptor instead.
func (*SubscribeTopicRequest) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{12}
}

func (x *SubscribeTopicRequest) GetTopicId() []int64 {
	if x != nil {
		return x.TopicId
	}
	return nil
}

func (x *SubscribeTopicRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubscribeTopicRequest) GetFromMessageId() int64 {
	if x != nil {
		return x.FromMessageId
	}
	return 0
}

func (x *SubscribeTopicRequest) GetSubscribeToken() string {
	if x != nil {
		return x.SubscribeToken
	}
	return ""
}

type SubscriptionNodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TopicId       []int64                `protobuf:"varint,2,rep,packed,name=topic_id,json=topicId,proto3" json:"topic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscriptionNodeRequest) Reset() {
	*x = SubscriptionNodeRequest{}
	mi := &file_protobufStorage_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionNodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionNodeRequest) ProtoMessage() {}

func (x *SubscriptionNodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionNodeRequest.ProtoReflect.Descriptor instead.
func (*SubscriptionNodeRequest) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{13}
}

func (x *SubscriptionNodeRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *SubscriptionNodeRequest) GetTopicId() []int64 {
	if x != nil {
		return x.TopicId
	}
	return nil
}

type SubscriptionNodeResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SubscribeToken string                 `protobuf:"bytes,1,opt,name=subscribe_token,json=subscribeToken,proto3" json:"subscribe_token,omitempty"` // subscription token to be presented to the returned node
	Node           *NodeInfo              `protobuf:"bytes,2,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SubscriptionNodeResponse) Reset() {
	*x = SubscriptionNodeResponse{}
	mi := &file_protobufStorage_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscriptionNodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscriptionNodeResponse) ProtoMessage() {}

func (x *SubscriptionNodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscriptionNodeResponse.ProtoReflect.Descriptor instead.
func (*SubscriptionNodeResponse) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{14}
}

func (x *SubscriptionNodeResponse) GetSubscribeToken() string {
	if x != nil {
		return x.SubscribeToken
	}
	return ""
}

func (x *SubscriptionNodeResponse) GetNode() *NodeInfo {
	if x != nil {
		return x.Node
	}
	return nil
}

type MessageEvent struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int64                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"` // monotonically increasing event number
	Op             OpType                 `protobuf:"varint,2,opt,name=op,proto3,enum=razpravljalnica.OpType" json:"op,omitempty"`                   // type of event
	Message        *Message               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	EventAt        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=event_at,json=eventAt,proto3" json:"event_at,omitempty"` // timestamp of the event
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MessageEvent) Reset() {
	*x = MessageEvent{}
	mi := &file_protobufStorage_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageEvent) ProtoMessage() {}

func (x *MessageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageEvent.ProtoReflect.Descriptor instead.
func (*MessageEvent) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{15}
}

func (x *MessageEvent) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *MessageEvent) GetOp() OpType {
	if x != nil {
		return x.Op
	}
	return OpType_OP_POST
}

func (x *MessageEvent) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *MessageEvent) GetEventAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EventAt
	}
	return nil
}

type GetUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserRequest) Reset() {
	*x = GetUserRequest{}
	mi := &file_protobufStorage_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserRequest) ProtoMessage() {}

func (x *GetUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserRequest.ProtoReflect.Descriptor instead.
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{16}
}

func (x *GetUserRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ReplicateWriteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int64                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Op             OpType                 `protobuf:"varint,2,opt,name=op,proto3,enum=razpravljalnica.OpType" json:"op,omitempty"` // OP_POST or OP_LIKE
	Message        *Message               `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplicateWriteRequest) Reset() {
	*x = ReplicateWriteRequest{}
	mi := &file_protobufStorage_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateWriteRequest) ProtoMessage() {}

func (x *ReplicateWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateWriteRequest.ProtoReflect.Descriptor instead.
func (*ReplicateWriteRequest) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{17}
}

func (x *ReplicateWriteRequest) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *ReplicateWriteRequest) GetOp() OpType {
	if x != nil {
		return x.Op
	}
	return OpType_OP_POST
}

func (x *ReplicateWriteRequest) GetMessage() *Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ReplicateWriteRequest) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type ReplicateWriteAck struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SequenceNumber int64                  `protobuf:"varint,1,opt,name=sequence_number,json=sequenceNumber,proto3" json:"sequence_number,omitempty"`
	Success        bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplicateWriteAck) Reset() {
	*x = ReplicateWriteAck{}
	mi := &file_protobufStorage_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateWriteAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateWriteAck) ProtoMessage() {}

func (x *ReplicateWriteAck) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateWriteAck.ProtoReflect.Descriptor instead.
func (*ReplicateWriteAck) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{18}
}

func (x *ReplicateWriteAck) GetSequenceNumber() int64 {
	if x != nil {
		return x.SequenceNumber
	}
	return 0
}

func (x *ReplicateWriteAck) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ReplicateWriteAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ServerRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerAddress string                 `protobuf:"bytes,1,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	Role          ServerRole             `protobuf:"varint,2,opt,name=role,proto3,enum=razpravljalnica.ServerRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerRegistration) Reset() {
	*x = ServerRegistration{}
	mi := &file_protobufStorage_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerRegistration) ProtoMessage() {}

func (x *ServerRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerRegistration.ProtoReflect.Descriptor instead.
func (*ServerRegistration) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{19}
}

func (x *ServerRegistration) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *ServerRegistration) GetRole() ServerRole {
	if x != nil {
		return x.Role
	}
	return ServerRole_HEAD
}

type ServerStatus struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ServerAddress       string                 `protobuf:"bytes,1,opt,name=server_address,json=serverAddress,proto3" json:"server_address,omitempty"`
	ActiveSubscriptions int64                  `protobuf:"varint,2,opt,name=active_subscriptions,json=activeSubscriptions,proto3" json:"active_subscriptions,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ServerStatus) Reset() {
	*x = ServerStatus{}
	mi := &file_protobufStorage_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerStatus) ProtoMessage() {}

func (x *ServerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerStatus.ProtoReflect.Descriptor instead.
func (*ServerStatus) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{20}
}

func (x *ServerStatus) GetServerAddress() string {
	if x != nil {
		return x.ServerAddress
	}
	return ""
}

func (x *ServerStatus) GetActiveSubscriptions() int64 {
	if x != nil {
		return x.ActiveSubscriptions
	}
	return 0
}

type ServerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Role          ServerRole             `protobuf:"varint,2,opt,name=role,proto3,enum=razpravljalnica.ServerRole" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerInfo) Reset() {
	*x = ServerInfo{}
	mi := &file_protobufStorage_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfo) ProtoMessage() {}

func (x *ServerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfo.ProtoReflect.Descriptor instead.
func (*ServerInfo) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{21}
}

func (x *ServerInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ServerInfo) GetRole() ServerRole {
	if x != nil {
		return x.Role
	}
	return ServerRole_HEAD
}

type GetClusterStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Head          *NodeInfo              `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Tail          *NodeInfo              `protobuf:"bytes,2,opt,name=tail,proto3" json:"tail,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterStateResponse) Reset() {
	*x = GetClusterStateResponse{}
	mi := &file_protobufStorage_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterStateResponse) ProtoMessage() {}

func (x *GetClusterStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protobufStorage_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterStateResponse.ProtoReflect.Descriptor instead.
func (*GetClusterStateResponse) Descriptor() ([]byte, []int) {
	return file_protobufStorage_proto_rawDescGZIP(), []int{22}
}

func (x *GetClusterStateResponse) GetHead() *NodeInfo {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *GetClusterStateResponse) GetTail() *NodeInfo {
	if x != nil {
		return x.Tail
	}
	return nil
}

var File_protobufStorage_proto protoreflect.FileDescriptor

const file_protobufStorage_proto_rawDesc = "" +
	"\n" +
	"\x15protobufStorage.proto\x12\x0frazpravljalnica\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"*\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"+\n" +
	"\x05Topic\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xb2\x01\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x19\n" +
	"\btopic_id\x18\x02 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x14\n" +
	"\x05likes\x18\x06 \x01(\x05R\x05likes\"Y\n" +
	"\x04Like\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"=\n" +
	"\bNodeInfo\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"'\n" +
	"\x11CreateUserRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"(\n" +
	"\x12CreateTopicRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\\\n" +
	"\x12PostMessageRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"g\n" +
	"\x12LikeMessageRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12\x1d\n" +
	"\n" +
	"message_id\x18\x02 \x01(\x03R\tmessageId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x03R\x06userId\"D\n" +
	"\x12ListTopicsResponse\x12.\n" +
	"\x06topics\x18\x01 \x03(\v2\x16.razpravljalnica.TopicR\x06topics\"m\n" +
	"\x12GetMessagesRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x01(\x03R\atopicId\x12&\n" +
	"\x0ffrom_message_id\x18\x02 \x01(\x03R\rfromMessageId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"K\n" +
	"\x13GetMessagesResponse\x124\n" +
	"\bmessages\x18\x01 \x03(\v2\x18.razpravljalnica.MessageR\bmessages\"\x9c\x01\n" +
	"\x15SubscribeTopicRequest\x12\x19\n" +
	"\btopic_id\x18\x01 \x03(\x03R\atopicId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12&\n" +
	"\x0ffrom_message_id\x18\x03 \x01(\x03R\rfromMessageId\x12'\n" +
	"\x0fsubscribe_token\x18\x04 \x01(\tR\x0esubscribeToken\"M\n" +
	"\x17SubscriptionNodeRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x19\n" +
	"\btopic_id\x18\x02 \x03(\x03R\atopicId\"r\n" +
	"\x18SubscriptionNodeResponse\x12'\n" +
	"\x0fsubscribe_token\x18\x01 \x01(\tR\x0esubscribeToken\x12-\n" +
	"\x04node\x18\x02 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04node\"\xcb\x01\n" +
	"\fMessageEvent\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x03R\x0esequenceNumber\x12'\n" +
	"\x02op\x18\x02 \x01(\x0e2\x17.razpravljalnica.OpTypeR\x02op\x122\n" +
	"\amessage\x18\x03 \x01(\v2\x18.razpravljalnica.MessageR\amessage\x125\n" +
	"\bevent_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\aeventAt\" \n" +
	"\x0eGetUserRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\xd7\x01\n" +
	"\x15ReplicateWriteRequest\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x03R\x0esequenceNumber\x12'\n" +
	"\x02op\x18\x02 \x01(\x0e2\x17.razpravljalnica.OpTypeR\x02op\x122\n" +
	"\amessage\x18\x03 \x01(\v2\x18.razpravljalnica.MessageR\amessage\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"{\n" +
	"\x11ReplicateWriteAck\x12'\n" +
	"\x0fsequence_number\x18\x01 \x01(\x03R\x0esequenceNumber\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"l\n" +
	"\x12ServerRegistration\x12%\n" +
	"\x0eserver_address\x18\x01 \x01(\tR\rserverAddress\x12/\n" +
	"\x04role\x18\x02 \x01(\x0e2\x1b.razpravljalnica.ServerRoleR\x04role\"h\n" +
	"\fServerStatus\x12%\n" +
	"\x0eserver_address\x18\x01 \x01(\tR\rserverAddress\x121\n" +
	"\x14active_subscriptions\x18\x02 \x01(\x03R\x13activeSubscriptions\"W\n" +
	"\n" +
	"ServerInfo\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12/\n" +
	"\x04role\x18\x02 \x01(\x0e2\x1b.razpravljalnica.ServerRoleR\x04role\"w\n" +
	"\x17GetClusterStateResponse\x12-\n" +
	"\x04head\x18\x01 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04head\x12-\n" +
	"\x04tail\x18\x02 \x01(\v2\x19.razpravljalnica.NodeInfoR\x04tail*K\n" +
	"\x06OpType\x12\v\n" +
	"\aOP_POST\x10\x00\x12\v\n" +
	"\aOP_LIKE\x10\x01\x12\x12\n" +
	"\x0eOP_CREATE_USER\x10\x02\x12\x13\n" +
	"\x0fOP_CREATE_TOPIC\x10\x03*,\n" +
	"\n" +
	"ServerRole\x12\b\n" +
	"\x04HEAD\x10\x00\x12\n" +
	"\n" +
	"\x06MIDDLE\x10\x01\x12\b\n" +
	"\x04TAIL\x10\x022\x82\x05\n" +
	"\fMessageBoard\x12G\n" +
	"\n" +
	"CreateUser\x12\".razpravljalnica.CreateUserRequest\x1a\x15.razpravljalnica.User\x12J\n" +
	"\vCreateTopic\x12#.razpravljalnica.CreateTopicRequest\x1a\x16.razpravljalnica.Topic\x12L\n" +
	"\vPostMessage\x12#.razpravljalnica.PostMessageRequest\x1a\x18.razpravljalnica.Message\x12L\n" +
	"\vLikeMessage\x12#.razpravljalnica.LikeMessageRequest\x1a\x18.razpravljalnica.Message\x12A\n" +
	"\aGetUser\x12\x1f.razpravljalnica.GetUserRequest\x1a\x15.razpravljalnica.User\x12I\n" +
	"\n" +
	"ListTopics\x12\x16.google.protobuf.Empty\x1a#.razpravljalnica.ListTopicsResponse\x12X\n" +
	"\vGetMessages\x12#.razpravljalnica.GetMessagesRequest\x1a$.razpravljalnica.GetMessagesResponse\x12Y\n" +
	"\x0eSubscribeTopic\x12&.razpravljalnica.SubscribeTopicRequest\x1a\x1d.razpravljalnica.MessageEvent0\x012\x84\x04\n" +
	"\fControlPlane\x12S\n" +
	"\x0fGetClusterState\x12\x16.google.protobuf.Empty\x1a(.razpravljalnica.GetClusterStateResponse\x12M\n" +
	"\x0eRegisterServer\x12#.razpravljalnica.ServerRegistration\x1a\x16.google.protobuf.Empty\x12D\n" +
	"\rGetHeadServer\x12\x16.google.protobuf.Empty\x1a\x1b.razpravljalnica.ServerInfo\x12L\n" +
	"\x15GetSubscriptionServer\x12\x16.google.protobuf.Empty\x1a\x1b.razpravljalnica.ServerInfo\x12P\n" +
	"\x17ReportSubscriptionCount\x12\x1d.razpravljalnica.ServerStatus\x1a\x16.google.protobuf.Empty\x12j\n" +
	"\x13GetSubscriptionNode\x12(.razpravljalnica.SubscriptionNodeRequest\x1a).razpravljalnica.SubscriptionNodeResponse2p\n" +
	"\x10ChainReplication\x12\\\n" +
	"\x0eReplicateWrite\x12&.razpravljalnica.ReplicateWriteRequest\x1a\".razpravljalnica.ReplicateWriteAckB:Z8github.com/AuraDvin/razpravljalnica/grpc/protobufStorageb\x06proto3"

var (
	file_protobufStorage_proto_rawDescOnce sync.Once
	file_protobufStorage_proto_rawDescData []byte
)

func file_protobufStorage_proto_rawDescGZIP() []byte {
	file_protobufStorage_proto_rawDescOnce.Do(func() {
		file_protobufStorage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protobufStorage_proto_rawDesc), len(file_protobufStorage_proto_rawDesc)))
	})
	return file_protobufStorage_proto_rawDescData
}

var file_protobufStorage_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_protobufStorage_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_protobufStorage_proto_goTypes = []any{
	(OpType)(0),                      // 0: razpravljalnica.OpType
	(ServerRole)(0),                  // 1: razpravljalnica.ServerRole
	(*User)(nil),                     // 2: razpravljalnica.User
	(*Topic)(nil),                    // 3: razpravljalnica.Topic
	(*Message)(nil),                  // 4: razpravljalnica.Message
	(*Like)(nil),                     // 5: razpravljalnica.Like
	(*NodeInfo)(nil),                 // 6: razpravljalnica.NodeInfo
	(*CreateUserRequest)(nil),        // 7: razpravljalnica.CreateUserRequest
	(*CreateTopicRequest)(nil),       // 8: razpravljalnica.CreateTopicRequest
	(*PostMessageRequest)(nil),       // 9: razpravljalnica.PostMessageRequest
	(*LikeMessageRequest)(nil),       // 10: razpravljalnica.LikeMessageRequest
	(*ListTopicsResponse)(nil),       // 11: razpravljalnica.ListTopicsResponse
	(*GetMessagesRequest)(nil),       // 12: razpravljalnica.GetMessagesRequest
	(*GetMessagesResponse)(nil),      // 13: razpravljalnica.GetMessagesResponse
	(*SubscribeTopicRequest)(nil),    // 14: razpravljalnica.SubscribeTopicRequest
	(*SubscriptionNodeRequest)(nil),  // 15: razpravljalnica.SubscriptionNodeRequest
	(*SubscriptionNodeResponse)(nil), // 16: razpravljalnica.SubscriptionNodeResponse
	(*MessageEvent)(nil),             // 17: razpravljalnica.MessageEvent
	(*GetUserRequest)(nil),           // 18: razpravljalnica.GetUserRequest
	(*ReplicateWriteRequest)(nil),    // 19: razpravljalnica.ReplicateWriteRequest
	(*ReplicateWriteAck)(nil),        // 20: razpravljalnica.ReplicateWriteAck
	(*ServerRegistration)(nil),       // 21: razpravljalnica.ServerRegistration
	(*ServerStatus)(nil),             // 22: razpravljalnica.ServerStatus
	(*ServerInfo)(nil),               // 23: razpravljalnica.ServerInfo
	(*GetClusterStateResponse)(nil),  // 24: razpravljalnica.GetClusterStateResponse
	(*timestamppb.Timestamp)(nil),    // 25: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 26: google.protobuf.Empty
}
var file_protobufStorage_proto_depIdxs = []int32{
	25, // 0: razpravljalnica.Message.created_at:type_name -> google.protobuf.Timestamp
	3,  // 1: razpravljalnica.ListTopicsResponse.topics:type_name -> razpravljalnica.Topic
	4,  // 2: razpravljalnica.GetMessagesResponse.messages:type_name -> razpravljalnica.Message
	6,  // 3: razpravljalnica.SubscriptionNodeResponse.node:type_name -> razpravljalnica.NodeInfo
	0,  // 4: razpravljalnica.MessageEvent.op:type_name -> razpravljalnica.OpType
	4,  // 5: razpravljalnica.MessageEvent.message:type_name -> razpravljalnica.Message
	25, // 6: razpravljalnica.MessageEvent.event_at:type_name -> google.protobuf.Timestamp
	0,  // 7: razpravljalnica.ReplicateWriteRequest.op:type_name -> razpravljalnica.OpType
	4,  // 8: razpravljalnica.ReplicateWriteRequest.message:type_name -> razpravljalnica.Message
	25, // 9: razpravljalnica.ReplicateWriteRequest.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 10: razpravljalnica.ServerRegistration.role:type_name -> razpravljalnica.ServerRole
	1,  // 11: razpravljalnica.ServerInfo.role:type_name -> razpravljalnica.ServerRole
	6,  // 12: razpravljalnica.GetClusterStateResponse.head:type_name -> razpravljalnica.NodeInfo
	6,  // 13: razpravljalnica.GetClusterStateResponse.tail:type_name -> razpravljalnica.NodeInfo
	7,  // 14: razpravljalnica.MessageBoard.CreateUser:input_type -> razpravljalnica.CreateUserRequest
	8,  // 15: razpravljalnica.MessageBoard.CreateTopic:input_type -> razpravljalnica.CreateTopicRequest
	9,  // 16: razpravljalnica.MessageBoard.PostMessage:input_type -> razpravljalnica.PostMessageRequest
	10, // 17: razpravljalnica.MessageBoard.LikeMessage:input_type -> razpravljalnica.LikeMessageRequest
	18, // 18: razpravljalnica.MessageBoard.GetUser:input_type -> razpravljalnica.GetUserRequest
	26, // 19: razpravljalnica.MessageBoard.ListTopics:input_type -> google.protobuf.Empty
	12, // 20: razpravljalnica.MessageBoard.GetMessages:input_type -> razpravljalnica.GetMessagesRequest
	14, // 21: razpravljalnica.MessageBoard.SubscribeTopic:input_type -> razpravljalnica.SubscribeTopicRequest
	26, // 22: razpravljalnica.ControlPlane.GetClusterState:input_type -> google.protobuf.Empty
	21, // 23: razpravljalnica.ControlPlane.RegisterServer:input_type -> razpravljalnica.ServerRegistration
	26, // 24: razpravljalnica.ControlPlane.GetHeadServer:input_type -> google.protobuf.Empty
	26, // 25: razpravljalnica.ControlPlane.GetSubscriptionServer:input_type -> google.protobuf.Empty
	22, // 26: razpravljalnica.ControlPlane.ReportSubscriptionCount:input_type -> razpravljalnica.ServerStatus
	15, // 27: razpravljalnica.ControlPlane.GetSubscriptionNode:input_type -> razpravljalnica.SubscriptionNodeRequest
	19, // 28: razpravljalnica.ChainReplication.ReplicateWrite:input_type -> razpravljalnica.ReplicateWriteRequest
	2,  // 29: razpravljalnica.MessageBoard.CreateUser:output_type -> razpravljalnica.User
	3,  // 30: razpravljalnica.MessageBoard.CreateTopic:output_type -> razpravljalnica.Topic
	4,  // 31: razpravljalnica.MessageBoard.PostMessage:output_type -> razpravljalnica.Message
	4,  // 32: razpravljalnica.MessageBoard.LikeMessage:output_type -> razpravljalnica.Message
	2,  // 33: razpravljalnica.MessageBoard.GetUser:output_type -> razpravljalnica.User
	11, // 34: razpravljalnica.MessageBoard.ListTopics:output_type -> razpravljalnica.ListTopicsResponse
	13, // 35: razpravljalnica.MessageBoard.GetMessages:output_type -> razpravljalnica.GetMessagesResponse
	17, // 36: razpravljalnica.MessageBoard.SubscribeTopic:output_type -> razpravljalnica.MessageEvent
	24, // 37: razpravljalnica.ControlPlane.GetClusterState:output_type -> razpravljalnica.GetClusterStateResponse
	26, // 38: razpravljalnica.ControlPlane.RegisterServer:output_type -> google.protobuf.Empty
	23, // 39: razpravljalnica.ControlPlane.GetHeadServer:output_type -> razpravljalnica.ServerInfo
	23, // 40: razpravljalnica.ControlPlane.GetSubscriptionServer:output_type -> razpravljalnica.ServerInfo
	26, // 41: razpravljalnica.ControlPlane.ReportSubscriptionCount:output_type -> google.protobuf.Empty
	16, // 42: razpravljalnica.ControlPlane.GetSubscriptionNode:output_type -> razpravljalnica.SubscriptionNodeResponse
	20, // 43: razpravljalnica.ChainReplication.ReplicateWrite:output_type -> razpravljalnica.ReplicateWriteAck
	29, // [29:44] is the sub-list for method output_type
	14, // [14:29] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_protobufStorage_proto_init() }
func file_protobufStorage_proto_init() {
	if File_protobufStorage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protobufStorage_proto_rawDesc), len(file_protobufStorage_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_protobufStorage_proto_goTypes,
		DependencyIndexes: file_protobufStorage_proto_depIdxs,
		EnumInfos:         file_protobufStorage_proto_enumTypes,
		MessageInfos:      file_protobufStorage_proto_msgTypes,
	}.Build()
	File_protobufStorage_proto = out.File
	file_protobufStorage_proto_goTypes = nil
	file_protobufStorage_proto_depIdxs = nil
}
